server:
  port: 8081

security:
  user:
    name: admin
    password: admin321

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin321@10.0.5.100:8761/eureka,http://admin:admin321@10.0.5.101:8761/eureka

feign:
  hystrix:
    enabled: true

  httpclient:
    enabled: true

auth:
  user: admin
  password: admin321